version: '3.4'
services:
  backend:
    build:
      context: ./
    volumes:
      - './:/app/'
    ports:
      - '3000:3000'
    depends_on:
      - 'postgres'
    networks:
      - webnet
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=ADMIN1234
      - POSTGRES_DB=Winnin-DB
    volumes:
      - './data:/var/lib/postgresql/data/'
    ports:
      - '5432:5432'
    restart: always
networks:
  webnet:
    driver: bridge
